# Generated by Django 2.2 on 2021-02-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_porfilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorfileFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
